### ISSUE TITLE
1.7.15 throws an react error

### ISSUE THREAD

**Issue by IgorBabkin** [konvajs/react-konva#258]
Uncaught Error: Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue.

**Comment by IgorBabkin** [comment]
17.14 is okay

**Comment by lavrton** [comment]
What versions of `react`, `react-dom` and `react-konva` are you using?

**Comment by IgorBabkin** [comment]
react: 16.5.2
react-dom: 16.4.2
react-konva: 1.7.15

**Comment by lavrton** [comment]
You have `react` and `react-dom` version mismatch. Try to update them.

**Comment by IgorBabkin** [comment]
doesn't work

**Comment by senthilmohith** [comment]
@lavrton,

I'm also getting the same error "Uncaught Error: Expected subtree parent to be a mounted class component. This error is likely caused by a bug in React. Please file an issue.". "The above error occurred in the <Stage> component".

I'm using the below versions,
react: 16.6.3
react-dom: 16.6.3
react-konva: 1.7.16

How to resolve this issue?

**Comment by lavrton** [comment]
update `react-konva`

**Comment by senthilmohith** [comment]
@lavrton, Which version I have to update?

**Comment by lavrton** [comment]
`16.6.31`

**Comment by senthilmohith** [comment]
@lavrton, It's working fine with 16.6.31. Thanks for the updates.

**Comment by ajeetku** [comment]
Version mismatch detected for react-konva and react. react-konva expects to have react version 16.6.3, but it has version 16.7.0
