### ISSUE TITLE
Properties requiring DOM elements should require React elements instead.

### ISSUE THREAD

**Issue by wouldntsavezion** [konvajs/react-konva#301]
I have a problem using the react version and I think it's really more about an implementation issue. Some properties, like [fillPatternImage](https://konvajs.github.io/api/Konva.Shape.html#fillPatternImage), expect a DOM element, in this case an image or a canvas, problem is, when using react, you don't have those, so there really isn't ever a situation where you can reliably use these properties in `react-konva`, unless you define these elements manually, in which case you might as well not use react at all. See the following simple JSX example, where even using a basic `image` jsx element does not work, as it's still not an actual DOM node :

```jsx
<Stage width={this.props.width} height={this.props.height}>
  <Layer>
    <Rect 
      width={this.props.width}
      height={this.props.height}
      fillPatternImage={<image />}
    />
  </Layer>
</Stage>
```

I think that in `react-konva` such props should somehow expect react version instead. I haven't yet looked into the code so I don't know how hard this would be to implement, but I will look into it soon.

If anyone has an alternative, please let me know.

**Comment by lavrton** [comment]
Yep, that is the implementation issue but currently, I don't see any ways to resolve it in a good way.

It is very easy to use `fillPatternImage`, but you have to create DOM element manually (for example in `componentDidMount`) and then use it in a render function. Similar as in image demo: https://konvajs.github.io/docs/react/Images.html

The solution is not beautiful, but it works well because you have full control what elements to use and how to use the. The element can be an image or a video or a canvas element.

Also in this approach you have full control what to do if image is not loaded.

**Comment by wouldntsavezion** [comment]
I understand this workaround but, as I said, creating the DOM element manually doesn't always make sense. It does when using an image or another static source, but in my case I would like to use another canvas created with `react-konva` and potentially having content spread across multiple react components. 

I can work my way around it, but being able to simply use the react components instead would not only be easier, it would also make more sense in this context.

I've looked into the code and I also don't know how to resolve it.

**Comment by lavrton** [comment]
For the current moment, I don't see good ways to resolve that issue. Defining images in jsx looks good, but it doesn't cover many other cases, like using video or canvas for `fillPatternImage` property.
