### ISSUE TITLE
Attempting to free draw an Arrow

### ISSUE THREAD

**Issue by michaelcukier** [konvajs/react-konva#345]
Hey,

I'm trying to create a functionality where the user draws an Arrow by choosing point A with his mouse and drag it to point B. 

This is exactly what I'm trying to do: https://jsfiddle.net/w33e9fpa/, but I can't seem to figure out how to convert this code to React code.

My WIP is here: https://codesandbox.io/s/3yzv9jm9o5

Thanks for you help !

**Comment by ejarzo** [comment]
Hey, it looks like you are trying to manipulate the canvas manually using Konva's API. Using react-konva, we should very rarely have to do this. The idea is that we want to use `state` to represent what is on our canvas, and let the `render` function take care of the rest. 

I put together a fork of your demo here: https://codesandbox.io/s/vyw38lxw77 (note: I also updated the dependencies to the latest versions). Using handlers on the wrapping component, we can get the mouse position values and set them in `state`. Then, in `render` we simply pass them into a `CustomArrow` component which renders the arrow based on the start position and end position.

The example only renders one arrow. To render a new arrow every time you drag and release, you will need to establish an array of positions in the `state`. In the mouseDown handler, instead of changing the current position, you can push a new position to the array. In `render` you can then then map over that array to render one `CustomArrow` for each element. Docs for rendering lists: https://reactjs.org/docs/lists-and-keys.html#rendering-multiple-components.

**Comment by lavrton** [comment]
@ejarzo very good demo. Thanks for sharing. I hope it resolves the question.
