### ISSUE TITLE
Stage is killing the Context

### ISSUE THREAD

**Issue by macabeus** [konvajs/react-konva#349]
I'm developing a project using provider pattern. So I'm passing informations between my components using context.

Then, at `Map` component I have this:

```js
const Map = () => {
  const { ... } = useContext(VisionContext).vision // I can use VisionContext here

  return (
    <Fragment>
      <Stage>
        <TilemapLayer />
    ...
  )
}
```

And for some unknown reason, I have a problem at `TilemapLayer` because the context didn't arrive at this component:

```js
const TilemapLayer = ({ setSelectedPointInfos }) => {
  const { ... } = useContext(VisionContext).vision // Error! "useContext(VisionContext)" returns "undefined" here!
```

Debugging it I replaced the `Stage` to `div` at return of `Map`:

```js
const Map = () => {
  ...

  return (
    <Fragment>
      <div>
        <TilemapLayer />
    ...
  )
}
```

And with this code, I can use `useContext(VisionContext)` at `TilemapLayer`. I tried replacing `div` for others components as well, and it's worked.

Because of it, I think that `Stage` is killing the Context - what is a bug.

**Comment by lavrton** [comment]
`react-konva` is a custom renderer. At the current moment, it can't have access to contexts of the parent tree. I can't find a way to may it work automatically.

So `react-konva` reset all the stack. The good news is that you can "bridge" contexts manually. The idea is simple. Consume the context BEFORE `Stage` component. Then provide it again (with the same value) INSIDE `Stage`:


```javascript
const Canvas = () => {
  return (
    <ThemeContext.Consumer>
      {value => (
        <Stage width={window.innerWidth} height={window.innerHeight}>
          <ThemeContext.Provider value={value}>
            <Layer>
              <ThemedRect />
            </Layer>
          </ThemeContext.Provider>
        </Stage>
      )}
    </ThemeContext.Consumer>
  );
};
```

Demo: https://codesandbox.io/s/ykqw8r4r21

**Comment by ribx** [comment]
I was checking for this issue and saw that other libraries use the `getPublicRootInstance` function, when they render their root element:

https://github.com/facebook/react/blob/master/packages/react-dom/src/client/ReactDOM.js#L584

while `react-konva` uses
```
https://github.com/konvajs/react-konva/blob/master/src/ReactKonvaCore.js#L89-L99
```
to render the stage into the div given by the ref.

Do I understand this correctly?

**Comment by ribx** [comment]
Maybe this implementation would help:

https://github.com/michalochman/react-pixi-fiber/blob/master/src/Stage.js#L59-L74

**Comment by lavrton** [comment]
@ribx how it may help? `react-pixi-fiber` supports fully contexts?

**Comment by ribx** [comment]
I thought it does. I found it only because of this PR:

https://github.com/michalochman/react-pixi-fiber/pull/84/commits

But maybe things changed again in `react-reconciler`. Many projects using it, but there is no documentation provided by facebook yet.

So I will go for replicating all my providers. Thanks.

**Comment by lavrton** [comment]
Update on this issue. From `react-konva@18.2.2`, context bridge should work by default. It will be really cool if someone can try it and provide feedback.

**Comment by BryceDalbey** [comment]
I've just tried it out with `react-konva@18.2.2` and had no problems. I also bridged into the `<Html>` wrapper with no issues, though I haven't tested that as much.

Not sure this is the right place for this but just in case others are doing the same as me: I originally bridged into the stage to use a customization menu from outside the stage but once I had enough elements inside the stage (~15 1000x500px partly transparent images with RGB filters) the latency became noticeable (since every component in the stage would run on each state update). So I moved the menu inside the stage and separated it out so I could wrap each part and the layers it interacts in a separate context (hence having to bridge into html wrappers). This way makes organizing the menu a pain since each part is inside a separate html wrapper but the performance is obviously much better.
