### ISSUE TITLE
Direct changes to canvas get lost

### ISSUE THREAD

**Issue by sergiulucaci** [konvajs/react-konva#376]
Hi guys, 

first of all, congrats for this rockin library. 

I'm trying to make some changes directly to `<canvas />` element generated by konva, but whenever konva layer is making some updates, "direct changes" get lost.

Eg:

```
componentDidMount() {
  const canvas = this.layer.getCanvas()._canvas;
  const cx = canvas.getContext('2d');

  canvas.addEventListener('mousedown', event => {
    // any changes to canvas, like  cx.fillRect or cx.fillStyle will be lost if new konva elements are added
  });
}

render() {
  <Stage
    // props goes gere
  >
    <Layer ref={ref => { this.layer = ref; } }>
      // konva elements goes here        
    </Layer>
  </Stage>
}
```

Can konva "keep in mind" the changes made directly to its generated canvas when new konva elements are pushed into layer / when konva elements elements are updated? 

This is a more complex example where I have this problem: 
https://codesandbox.io/s/stoic-dubinsky-dyf2o.

Steps to reproduce:
1. Create a circle using "Draw Circles" tool
2. Fill it Using "Paint Bucket" tool 
3. Create another circle using "Draw Circles" tool
4. The changes made to the first circle get lost

Thank you in advance!

**Comment by lavrton** [comment]
`Konva` can't remember your additional drawings. And it will clear the canvas on any new drawing. If you want to draw into canvas directly you should use a custom `Konva.Shape` (https://konvajs.org/docs/react/Custom_Shape.html) or you can create an offscreen canvas and use it for `Konva.Image`. So instead of drawing into layer directly just create a new canvas element and draw into it.

**Comment by lavrton** [comment]
https://konvajs.org/docs/sandbox/Native_Context_Access.html
