### ISSUE TITLE
Pieces loading

### ISSUE THREAD

**Issue by ggpo1** [konvajs/react-konva#443]
Is it possible to load stage by pieces or chunks?

**Comment by lavrton** [comment]
I think so. But you have to do it manually.

In one app I had slow initial loading. Because I had A LOT of elements to show. The first render was very slow. So I did this:

1. Create an app with empty list of items (so just the stage is visible on the screen).
2. Load items from somewhere (like a network, local storage) but do not add them into the state
3. Append items into a react state by small junks with a timeout:


```javascript
componentDidMount() {
  const allItems = loadData();

  
  setInterval(() => {
      this.setState({
        // draw next 20 items
        items: allItems.slice(0, this.state.items.length + 20);
      });
      // need to add code to cancel iterval
   }, 300);
}
```

**Comment by ggpo1** [comment]
Thank you.
