### ISSUE TITLE
Drawing path on canvas as custom shape and use events

### ISSUE THREAD

**Issue by Bluefitdev** [konvajs/react-konva#470]
Hey Anton,

Recently my workplace has been trying to draw some stuff and after searching for a lot of libraries out there I have come down to use Konva. You seem to be very active to answer issues and really put a hard work on it! Thanks for that!

I had my time to follow the documentation and play around with the shape given in react components, however right now we are trying to draw a custom svg of human body looking more or less like this:

I figure we can't really use custom shape with this? Because it is SVG file. So I had a look at the SVG documentation, the only possible solution is to draw it as path, am i correct?

If so, how do I add events to each different part of the body? Let's say onMouseOver I want each part of the body to change color like what we can do with Rect, and other shapes.

Do I need different component for different part of the body?

Any help will be appreciated

Cheers mate

<img width="500" alt="Screen Shot 2020-05-15 at 8 58 25 am" src="https://user-images.githubusercontent.com/56941349/81994203-a9fffa80-968a-11ea-8b0f-273d0515413e.png">

**Comment by lavrton** [comment]
Thanks for your kind words.

In the SVG demos, we have a whole SVG image treated as one object. It that case it can't have listeners for its areas.

So probably it will be just simpler to use SVG instead of canvas and `react-konva`. You just need to convert the SVG file into react components. Probably you can do it manually.

Or you can try to parse SVG file (there are many libs and native functions for that) and find all `<path/>` elements inside it. Then get path data from them and use them for `Konva.Path`.

**Comment by Bluefitdev** [comment]
Hey @lavrton,

I manage to do it using Konva.Path, but yes I have to extract each of them manually. It looks simpler to me with the wrapper you created compared to the use of SVG by itself

Thanks for the clarification!
