### ISSUE TITLE
Incorrect transformer position when text is offset

### ISSUE THREAD

**Issue by pasih** [konvajs/react-konva#498]
When transforming a group that contains offset text, the transformer box is initially drawn incorrectly. Once you apply any transformation (mouse down on the rotate handle is sufficient I think), the bounding box is updated correctly.

Reproduction: https://codesandbox.io/s/konva-and-svg-demo-o1nz7?file=/src/Playground.js - when page loads, the transformer is incorrectly positioned. When you touch the handle, it fixes itself.

This could actually be more of a Konva issue than a react-konva one but because the reproduction is pretty trivial, you can probably tell where the issue is from just looking at it.

Many, many thanks for working on such a superb library!

**Comment by lavrton** [comment]
I see. Unfortunately, at the current moment, the `Transformer` can't track internal changes inside the group. It just doesn't know that Text properties are changed (because it tracks only group properties). As soon I you touch/move the group the `Transfomer` is doing recalculations.

Probably `Konva` will support that case automatically one day.

For now you can just force update the transformed:

```js
  useEffect(() => {
    transformRef.current.forceUpdate();
  });
```

https://codesandbox.io/s/react-konva-force-update-transformer-126fh

**Comment by pasih** [comment]
Hm, right. My use case is actually little more complicated (essentially, the object already exists before the transformer is created - it's enabled on click). For some reason just adding the `forceUpdate` there isn't working for me (I did check that the `useEffect` actually fires). I need to investigate a bit more.

**Comment by lavrton** [comment]
I am going to close the issue for now. Let me know if you still have an issue. If so, please provide a demo.
