### ISSUE TITLE
Support context api - (recoil)

### ISSUE THREAD

**Issue by softmarshmallow** [konvajs/react-konva#533]
using konva with internal state, useState works fine. but adopting recoil and useRecoilState starts to break thinks down. It just won't work. but many cases, canvas may refer a value from global state, and since recoil is pretty much the new standard of managing shared states, it might be nice to have context api support for react-konva.

Thougts? and technical barriers?

**Comment by softmarshmallow** [comment]
![image](https://user-images.githubusercontent.com/16307013/100426758-bdc5f800-30d4-11eb-823a-6d32e97722f3.png)
Error: This component must be used inside a <RecoilRoot> component.

**Comment by lavrton** [comment]
`react-konva` is a custom renderer. Because of the current React limitations, we have to "bridge" contexts. For more info read this: https://github.com/konvajs/react-konva#usage-with-react-context

Following this PR https://github.com/facebookexperimental/Recoil/pull/516, I made a working demo: https://codesandbox.io/s/react-konva-recoil-demo-r2kri?file=/src/App.js

**Comment by softmarshmallow** [comment]
Can you live this issue open until recoil releases the stabled version of the bridge?

**Comment by lavrton** [comment]
Please track it on the recoil repository. There is nothing we should do from `react-konva` side.

**Comment by softmarshmallow** [comment]
Alright, thanks

**Comment by lavrton** [comment]
Update on this issue. From `react-konva@18.2.2`, context bridge should work by default. It will be really cool if someone can try it and provide feedback.
