### ISSUE TITLE
[Question] Clone Stamp tool

### ISSUE THREAD

**Issue by ezalorsara** [konvajs/react-konva#561]
Is it possible to create a photoshop like Clone stamp tool in Konva Js. I didn't find any info 
to help me doing this.

**Comment by lavrton** [comment]
That may be very hard to do. In order to implement it, you will need to dive-in into native HTML5 canvas implementation and direct pixels manipulation. Such operations are out of Konva scope. If you will be able to implement it with the native canvas, you can always display resulted canvas on the stage as `Konva.Image`.
