### ISSUE TITLE
Getting Typescript errors by just upgrading packages

### ISSUE THREAD

**Issue by kuzkokov** [konvajs/react-konva#587]
Hi there! Thanks for all your work here, it's a really great package!

So, the thing is, my CI start getting TS errors. I looked closely at it and discovered that they were due to this package's latest updates. So I upgraded all the packages and start getting errors locally as well.
The thing is, that if you just run something like `yarn upgrade` this package will upgrade (in my case, from version `17.0.2-0` to `17.0.2-3`), but `konva` will remain the same version (in my case `7.2.5`) despite it set as `>=8` in peer dependencies.
I'm not sure if I am doing something wrong, but maybe your should versioning the latest updates here as major as well?

So far, I just locked this package on version `17.0.2-0`.

**Comment by lavrton** [comment]
I just published `react-konva@17.0.2-4` with a bigger `konva` version range. Let me know if it works for you.

**Comment by ianwijma** [comment]
Hey! 

First off, loving the project! Its so easy to use and gives you the power of canvas using regular react code.

Although not 100% sure if this is related to this issue. But since KonvaJS updated to 8.* I've been getting `Must use import to load ES Module` errors from the `/node_modules/react-konva/lib/ReactKonvaCore.js`.

I'm using the following versions: 
- react-konva: `17.0.2-4`
- konva: `8.0.1`

I also have `react-konva-utils` installed for testing purposes, but planning to remove it for now. This one is on version `0.1.5`

**Comment by ianwijma** [comment]
I've made a repo with an example of my issue: https://github.com/ianwijma/konva-react-import-issue

Here I'd like to point to the like I have added: https://github.com/ianwijma/konva-react-import-issue/blob/main/pages/index.js#L7
And here is the error I get from that project: https://github.com/ianwijma/konva-react-import-issue/blob/main/error-popup.png

To get to that point I have just installed NextJS using `npx create-next-app .` and then `yarn add react-konva konva` Where after I added the import to the `pages/index.js`, which resulted into the error in the image.

**Comment by lavrton** [comment]
Looks like nextJS doesn't like es modules yet. You may need to try this: https://www.npmjs.com/package/next-transpile-modules
