### ISSUE TITLE
resize while snapping from the left causes element to drag?

### ISSUE THREAD

**Issue by EssamEid614** [konvajs/react-konva#598]
first of all I would like to thank you for this amazing library but I have a very small issue with grid snapping

following the sandbox [here](https://codesandbox.io/s/react-konva-transformer-snapping-demo-yyfyr?file=/src/index.js)
resizing from the right anchors everything works as expected but if we start resizing from the left , the element gets dragged as well any idea why ? 

i also trying logging in the drag move however the element is not getting dragged so I am not sure why is this behavior occurring ?

**Comment by EssamEid614** [comment]
updated the [sandbox ](https://codesandbox.io/s/react-konva-transformer-snapping-demo-forked-ffife)to include snapping to x and y as well but it feels buggy any idea why?

**Comment by lavrton** [comment]
Because you may need a bit more complex solution. Also the behavior may be a bit different, depending on what anchor you move.

It get's tricky when you move anchors, that change `x` or `y` of a node. In that case, you can't just round `width` and `height`, you need to adjust them by `x` and `y` changes. It even gets more complex if your shape is rotated. That what worked for me for non-rotated shape.

```js
boundBoxFunc={(oldBox, newBox) => {
  const newX = Math.round(newBox.x / 10) * 10;
  const newY = Math.round(newBox.y / 10) * 10;

  const dx = newX - newBox.x;
  const dy = newY - newBox.y;

  newBox.x = newX;
  newBox.y = newY;

  newBox.width = Math.round((newBox.width - dx) / 10) * 10;
  newBox.height = Math.round((newBox.height - dy) / 10) * 10;

  return newBox;
}}
```

https://codesandbox.io/s/react-konva-transformer-snapping-demo-forked-zdtcv?file=/src/index.js

**Comment by rahuljsaliaan** [comment]
there are some bugs in this when the size of the shape becomes zero the shape just moves to the top left corner.
