### ISSUE TITLE
Proposal to add the ability to provide `absoluteX`, `absoluteY` values to any shape `props`.

### ISSUE THREAD

**Issue by MiiZZo** [konvajs/react-konva#643]
I can't understand why in Konva we can't pass `absoluteX`, `absoluteY` via `props`. Is there any reason?
```js
<Rect x={10} y={10} absoluteX={10} absoluteY={10} />
```

**Comment by lavrton** [comment]
Konva nodes don't have such attributes. That is why they are not presented in props. But Konva API has some methods to get/set absolute position. If you really need that properties, you can write your own simple wrapper.

```js
const AbsoluteRectangle = ({ absoluteX, absoluteY, ...rest }) => {
   const ref = React.useRef();
   React.useEffect(() => {
     ref.current.absolutePosition({
       x: absoluteX,
       y: absoluteY
     })
   }, [absoluteX, absoluteY])
   return <React ref={ref} {...rest} />;
}
```

Then use `<AbsoluteRectangle absoluteX={10} absoluteY={10} />`. 

Also you shouldn't use both relative and absolute positions in properties (as in your example). Because they may conflict. But it is better to have just one source of truth.
