### ISSUE TITLE
Changing zIndex of Image not working

### ISSUE THREAD

**Issue by tyt11123** [konvajs/react-konva#647]
Hi,

I tried to combine the features of these 4 examples into 1.
[https://konvajs.org/docs/react/Canvas_Export.html](https://konvajs.org/docs/react/Canvas_Export.html)
[https://konvajs.org/docs/react/Undo-Redo.html](https://konvajs.org/docs/react/Undo-Redo.html)
[https://konvajs.org/docs/react/zIndex.html](https://konvajs.org/docs/react/zIndex.html)
[https://konvajs.org/docs/react/Drop_Image.html](https://konvajs.org/docs/react/Drop_Image.html)

The code is here.
[https://codesandbox.io/s/konva-test-1-z9po4?file=/src/index.js](https://codesandbox.io/s/konva-test-1-z9po4?file=/src/index.js)

Now lions that are dropped into the stage cannot be dragged again.
The issue seems fixed if I disable onDragStart on line 140, but the zIndex of the lion cannot be changed then.

Any idea?

**Comment by lavrton** [comment]
It doesn't work because you are defining `URLImage` components INSIDE `App` component. It generates a new js function on every render -> React thinks that it is a new component -> it do unmount/mount -> it removes/create new Konva nodes -> dragging is disabled because original node was removed.

Fixed: https://codesandbox.io/s/konva-test-1-forked-i1o0lo?file=/src/index.js:1260-1263

**Comment by tyt11123** [comment]
Thanks so much.
Just made a common mistake that people directly learning React Hooks could easily make, indeed.
