### ISSUE TITLE
unable to transform image with snapping

### ISSUE THREAD

**Issue by devPhysics** [konvajs/react-konva#762]
I have found Shape snapping with React Konva on internet and tried to implement for Image. Problems are
1. Image is not draggable
2. when shape is dragged, image is flickering probably due to rerender. 
You can find  [code here](https://codesandbox.io/s/purple-mountain-hnydln)

**Comment by lavrton** [comment]
You need to move `URLImage` out from `App` component render. Otherwise it creates new function on every `App` render -> React thinks it is a new component -> React is doing full unmount/mount -> it breaks dragging and transforming logic.

https://codesandbox.io/s/react-konva-image-transformer-forked-vf2r73?file=/src/App.js
