### ISSUE TITLE
The collision algorithm is not working properly.

### ISSUE THREAD

**Issue by movie42** [konvajs/react-konva#766]
I'm using React-Konva to create a program that turns red when shapes intersect and otherwise returns to the default state. 

However, I followed the example on the [official website](https://konvajs.org/docs/sandbox/Collision_Detection.html) and it's not working correctly. 
The symptom is that it only turns red when it collides with the shape at the end of the array. 
The intersection works fine, so it comes out true (when it meets another shape), but it doesn't turn red. 
pleas help.... ㅜㅜ
I've put together an example code below.

**[example code](https://codesandbox.io/s/konva-collision-detection-2klyhp?file=/src/index.js)** 

ps. When initially rendered, the shapes are all overlapping. You can move them around.

**Comment by lavrton** [comment]
Because this is logic of your code:

```js
    e.currentTarget.children.forEach((rect) => {
      if (target === rect) {
        return;
      }

      if (haveIntersection(rect.getClientRect(), targetRect)) {
        target.setAttr("fill", "red");
      } else {
        target.setAttr("fill", "gray");
      }
    });
```

When an element is checked with the last element, its color will be changed to red or gray. But probably you should not change it to gray, if it is already was marked red with another shape. 

The Demo on the website is no changing color of dragging element.

If you want change change color of dragging element you may do this:

```js
const hasIntersection = e.currentTarget.children.find((rect) => {
  if (target === rect) {
    return false;
  }

  return haveIntersection(rect.getClientRect(), targetRect);
});
if (hasIntersection) {
  target.setAttr("fill", "red");
} else {
  target.setAttr("fill", "gray");
}
```
